
notify:
  extends: .notify

variables:
  COMPONENT: redis

.build:
  only:
  - feat/MDD-221

include:
  - project: 'MISP/helper-containers'
    ref: master
    file: '/.gitlab-ci-template.yml'
#
# For a cleaner Gitlab CI file include all subfolder which should be build:
#
  - '5-alpine3.9/.gitlab-ci.yml'
