language: minimal
dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  global:
  # The following variables are setup via gitlab project group:
  # - DOCKER_HUB_TOKEN
  # - DOCKER_SLUG
  # - DOCKER_USERNAME
  # - DOCKER_PASSWORD
  # - CUSTOM_REGISTRY_URL
  # - CUSTOM_REGISTRY_USER
  # - CUSTOM_REGISTRY_PWs
  matrix:
  - VERSION=5-alpine3.9


before_install:
- sudo .ci/01_before_install.sh

script:
# Download Images
- docker pull library/redis:$VERSION
# Retag
- docker tag redis:$VERSION $CUSTOM_REGISTRY_URL/misp-dockerized-redis:$VERSION
- docker tag redis:$VERSION $DOCKER_SLUG/misp-dockerized-redis:$VERSION
- docker images|grep redis
  
# don't notify me when things fail
notifications:
  email: false