variables:
    FOLDER: "5-alpine3.9"
    VERSION: "5-alpine3.9"
    TAGS: "${FOLDER}-dev"
    RELEASE_DATE: 2019-04

build 5-alpine3.9:
  extends: .build

test 5-alpine3.9:
  extends: .test
  only:
    changes:
    - 5-alpine3.9/*
    